// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteQT.Date;

#nullable disable

namespace TesteQT.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220608170453_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TesteQT.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Category");

                    b.Property<int>("DocumentCode")
                        .HasColumnType("int")
                        .HasColumnName("DocumentCode");

                    b.Property<string>("Files")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Files");

                    b.Property<int>("ProcessId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("ProcessId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("TesteQT.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("ProcessCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ProcessCode");

                    b.HasKey("Id");

                    b.ToTable("Process");
                });

            modelBuilder.Entity("TesteQT.Models.Document", b =>
                {
                    b.HasOne("TesteQT.Models.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");
                });
#pragma warning restore 612, 618
        }
    }
}
